### ISSUE TITLE
[BUG] I cant start the bot

### ISSUE THREAD

**Issue by Nikolai980** [sysdotini/hibiki#159]
SyntaxError: Unexpected token '.'
    at wrapSafe (internal/modules/cjs/loader.js:915:16)
    at Module._compile (internal/modules/cjs/loader.js:963:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/home/runner/hibiki/dist/src/classes/Client.js:27:16)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)

Help me fixing this

**Comment by YeetDevDiscord** [comment]
its an syntax error thats all

**Comment by lambdagg** [comment]
Hello,
As stated in our [README.md](https://github.com/sysdotini/hibiki#readme),

> Additionally, we don't support self-hosting or give support/answer questions for doing such. However, the bot is easily self hostable with some basic knowledge.

Have a nice day.
Lambdagg
